provider: {linux_aarch64: default, linux_ppc64le: default}
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IaED8CiL7VocX7WCWd2ORzlvRlI7JAXOqef7WG3BsRDdk9yLuswnm2JEXRIoYzG+B3XIb7NvjO2vdTWe7pq7R10E0b3JhCLJedLkGQLkoyOmVU5YsMRwO+iuzqYHkdgVG6NLc8rbAkkv0ZbSzzUv//Lxh6HX/iGhXfE7NtrwcmVC5fVJMivwaaNpl32mx1JGDOzOkcR4oDRVYlK3QrZVqCLENP/Voz0mfqs9PWB4Q4XzhsElgMPdVT3qwxGYfFPo1pllw9S2sQdnAU/aXIX25ZH+HY7aFJczx77KWtYaU4s3fljvCKJ7aUsoWLwlL/9vREQQH9ln02t1JHKb0PdoduAnIC2dGnM1BdF28CVQ0TM4xZbiPa9kkE/bOIzxjqDoGEaoGVMeMFwqi9Py9GUxJFeNl3tu9YK3yEsvdvRl43NHre5x3qXsWVn0ndqcbM3ukBtX/lhCeULho1DaNpitf6ziwdiaQtiFuyZITH6lJZJQOSYlC5hG7MEDny+AEwTmtQy+CQ6vXnHFA8JVkA8Ng0FNSq4Wv0x5FPO3yrYffJxs1KJXUj1RG6aJSvOp5rLAk6GYWM5wi1h6zzkYhGEyxzBq8gYVvj7P4WJ9Pq8C9mv9df6YsgYCWnvYyf9RlRq+iqUOn2fYD21hagmbfAHEVnFia5N8rLz0CXj9K1ABi5E=}
conda_forge_output_validation: false
